version: '3.7'

services:
  newswebsite:
    build:
      context: .
      dockerfile: NewsWebsite\Dockerfile
    depends_on: 
      - newsdatabase
  newsdatabase:
    image: ${DOCKER_REGISTRY-}microsoft/mssql-server-windows-express:1709